//
//  LocationListModels.swift
//  LocationFinder
//
//  Created by Monali on 22/06/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum LocationList
{
    // MARK: Use cases

    enum FetchLocations
    {
        struct Request
        {}

        struct Response
        {
            let locations : [location]

        }

        struct ViewModel
        {
            var displayedLocations: [DisplayedLocation]

            struct DisplayedLocation
            {
              var lat: Double
              var name: String
              var long: Double
            }
        }
    }
    
    // MARK: - Errors
    struct ErrorResponse {
        let error: LocationListError
    }
    
    struct ErrorViewModel {
        let errorTitle: String
        let errorMessage: String
    }
}

// MARK: - PlayerListError
enum LocationListError: Error {
    case serviceFailed(String)
}
