//
//  LocationListWorker.swift
//  LocationFinder
//
//  Created by Monali on 22/06/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LocationsWorkingLogic {
  /// Request to API for loading list of locations
    func fetchLocations(request: LocationList.FetchLocations.Request, _ completion: @escaping (Result<locationsResponseModel, Error>?) -> Void)
}


class LocationListWorker: LocationsWorkingLogic {
    // MARK: - Private Properties

    private let locationsService = StandardNetworkService(resourcePath: "main/locations.json")

    // MARK: - LocationsWorkingLogic

    func fetchLocations(request: LocationList.FetchLocations.Request, _ completion: @escaping (Result<locationsResponseModel, Error>?) -> Void) {

        locationsService.get { [weak self] (result: Result<locationsResponseModel, Error>) in
            DispatchQueue.main.async {
                guard self != nil else { return }
                
                switch result {
                case .success(let locations):
                    completion(.success(locations))
                    
                case .failure(let error):
                    completion(.failure(error))
                }
            }
        }
    }
}
